# Generated by Django 4.2.3 on 2023-07-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='Not Provided', max_length=254),
        ),
    ]
