# Generated by Django 4.2.3 on 2023-07-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_employer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='email',
        ),
        migrations.AddField(
            model_name='seeker',
            name='about',
            field=models.TextField(blank=True, default='Not Provided'),
        ),
    ]
