# Generated by Django 4.2.3 on 2023-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_employer_email_seeker_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='address',
            field=models.CharField(blank=True, default='Not Provided', max_length=400),
        ),
    ]
