# Generated by Django 4.2.3 on 2023-07-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant_email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='title',
        ),
    ]
